- name: Redfish job queue
  block:
    - name: Clear redfish job queues - {{ item }}
      shell:
        chdir: "{{ badfish_tempdir.path }}"
        cmd: |
          source {{ badfish_venv }}/bin/activate
          {{ badfish_cmd }}{{ item }} --clear-jobs --force
      register: clear_jobs
      until: clear_jobs is succeeded
      retries: 3
      delay: 30
  rescue:
    - name: Rescue - Reset iDRAC - {{ item }}
      shell: |
        sshpass -p "{{ lab_ipmi_password }}" ssh -o StrictHostKeyChecking=no {{ lab_ipmi_user }}@mgmt-{{ item }} "racadm racreset soft -f"
