- name: Set nodes to director boot order (Dell) - async
  shell: |
    {{ badfish_podman_cmd }}{{ item }} -t director ||
    sshpass -p "{{ lab_ipmi_password }}" ssh -o StrictHostKeyChecking=no {{ lab_ipmi_user }}@mgmt-{{ item }} "racadm racreset soft -f" &&
    {{ badfish_podman_cmd }}{{ item }} -t director
  async: 300
  poll: 0
  register: async_loop
  loop: "{{ dell_nodes }}"

- name: Wait for async task to finish
  async_status:
    jid: "{{ item.ansible_job_id }}"
  delay: 1
  retries: 30
  loop: "{{async_loop.results}}"
  register: async_loop_jobs
  until: async_loop_jobs.finished
