---
# vars file for shared-labs-ocp4-prep
yum_packages:
  - dnsmasq
  - podman
  - ipmitool
  - iptables-services
  - git
  - python3
  - python3-dns
  - python3-yaml
  - python3-urllib3
  - python3-requests
  - sshpass
  - make
rdo_packages: [] 

badfish_podman_cmd: "podman run --pull=always --rm quay.io/quads/badfish -u {{ lab_ipmi_user }} -p {{ lab_ipmi_password }} -i config/idrac_interfaces.yml -H mgmt-"
