---
# vars file for shared-labs-ocp4-prep
yum_packages:
  - dnsmasq
  - python3-dns
  - podman
  - ipmitool
  - iptables-services
  - python3-urllib3
  - python3-requests
badfish_cmd: "./badfish.py -u {{ lab_ipmi_user }} -p {{ lab_ipmi_password }} -i config/idrac_interfaces.yml -H mgmt-"
