- name: Create BMC secret definition file for new worker
  copy:
    dest: "{{ scaling_dir }}/worker-{{ ansible_loop.index0 + scale_worker_index | int }}-secret.yaml"
    content: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: "worker-{{ ansible_loop.index0 + scale_worker_index | int }}-bmc-secret"
        namespace: openshift-machine-api
      type: Opaque      
      data:
        username: "{{ lab_ipmi_user | b64encode }}"
        password: "{{ lab_ipmi_password | b64encode }}"
  loop: "{{ scale_worker_node.nodes }}"
  loop_control:
    extended: yes

- name: Apply BMC secrets for new worker
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc apply -f {{ scaling_dir }}/worker-{{ ansible_loop.index0 + scale_worker_index | int }}-secret.yaml
  loop: "{{ scale_worker_node.nodes }}"
  loop_control:
    extended: yes
