---
- name: Clean network interfaces created by lab automation
  shell: |
    /root/clean-interfaces.sh --nuke
  become: true
  ignore_errors: true

- name: Regather facts for updated interfaces
  setup:

- name: Get the bm mac address on provisioner node
  set_fact:
    bm_mac: "{{ hostvars[groups['orchestration'][0]]['ocpinv_content']['nodes'][0].mac[2] | lower }}"

- name: Get the bm provisioning address on provisioner node
  set_fact:
    prov_mac: "{{ hostvars[groups['orchestration'][0]]['ocpinv_content']['nodes'][0].mac[1] | lower }}"

- name: Set the lab public nic
  set_fact: 
    lab_pub_nic: "{{ ansible_default_ipv4['interface'] }}"

# Need to do this as the ansible facts per interface use the naming convention with _ and not -
- name: Set eligible interfaces list
  set_fact:
    ansible_eligible_interfaces: "{{ ansible_eligible_interfaces | default([]) + [item | replace('-','_')] }}"
  with_items:
    - "{{ ansible_interfaces }}"

- name: Get the bm interface
  set_fact:
    pub_nic: "{{ item }}"
  when: ansible_{{ item }}.macaddress is defined and ansible_{{ item}}.type == "ether" and ansible_{{ item }}.macaddress == bm_mac
  with_items:
    - "{{ ansible_eligible_interfaces }}"

- name: Get the provisioning interface
  set_fact:
    prov_nic: "{{ item }}"
  when: ansible_{{ item }}.macaddress is defined and ansible_{{ item }}.type == "ether" and ansible_{{ item }}.macaddress == prov_mac
  with_items:
    - "{{ ansible_eligible_interfaces }}"

- name: Set lab_pub_nics for master
  set_fact:
    lab_pub_nics: "{{ [lab_pub_nic] }}"

- name: Setting public nics for all workers
  block:
    - set_fact:
        lab_pub_nics:  "{{ lab_pub_nics + [ lab_vars['machine_types'][item.0][item.1]['pub_nic'] ]  }}"
      with_together: 
        - "{{ worker_vendors }}"
        - "{{ worker_types }}"
  vars:
    lab_vars: "{{ (lab_name == 'scale') | ternary(scale, alias) }}"
  when: lab_name in ['scale', 'alias']

- name: set disabled nics to lab_pub_nics
  set_fact:
    disable_nics: "{{ lab_pub_nics | unique }}"

