---
- name: Create root user SSH key path
  file:
   path: "{{ ssh_path }}"
   state: directory
   mode: 0755
  become: yes

- name: Generate SSH keypair for root user
  openssh_keypair:
    path: "{{ ssh_path }}/id_rsa"
    owner: root
    group: root
  become: yes

- name: Create kni user
  user:
    name: kni
    password: "{{ ansible_ssh_pass | password_hash('sha512') }}"

- name: Add kni to passwordless sudoers
  lineinfile:
    path: /etc/sudoers.d/kni
    line: kni ALL=(root) NOPASSWD:ALL
    create: yes
    mode: 0440
  become: yes

- name: Create kni user SSH key path
  file:
    path: /home/kni/.ssh
    state: directory
    mode: 0755
  become: yes

- name: Slurp the root user's SSH key
  slurp:
    src: "{{ ssh_path }}/id_rsa.pub"
  register: ssh_key

- name: Add root user SSH key to kni user
  authorized_key:
    user: kni
    state: present
    key:   "{{ ssh_key['content'] | b64decode }}"
  become: yes
