---
- name: IPI on Baremetal Installation Playbook -- Red Hat Shared Labs Edition
  hosts: provisioner
  roles:
  - shared-labs-prep
  - node-prep
  - installer

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy_list }}"
